### ISSUE TITLE
Barely readable when using a light theme

### ISSUE THREAD

**Issue by oschijns** [elevenhsoft/cosmic-ext-applet-ollama#11]
![screenshot-2024-08-16-16-59-01](https://github.com/user-attachments/assets/f732aef4-5d4e-46ce-93c2-d97891572062)

The applet use white text to display the conversation even when a light theme is enabled.
Which makes the text difficult to read.

**Comment by elevenhsoft** [comment]
Oh yeah. I did not test it properly, so we have an issue ^^ Right now I'm working on something else, but since I'm still on COSMIC I can look into this issue later :) Should not be hard to solve.

**Comment by elevenhsoft** [comment]
Also there is happening with markdown widget. Few weeks ago it was merged in Iced, so we should wait for libcosmic move. If we will have better markdown widget, there should be some improvements also.

**Comment by elevenhsoft** [comment]
Fixed it temporarily with this commit: https://github.com/elevenhsoft/cosmic-ext-applet-ollama/commit/091491f016eb13cb6594d6c54608d942edf2bef8
