### ISSUE TITLE
build never finish 

### ISSUE THREAD

**Issue by wiiznokes** [elevenhsoft/cosmic-ext-applet-ollama#4]

**Comment by wiiznokes** [comment]
nevermind

**Comment by elevenhsoft** [comment]
What happened? :P

**Comment by elevenhsoft** [comment]
About your previous comment with Fedora. Ollama is required only for runtime, for building it's not required at all.
Keep in mind, applets are building kind of longer than apps, soo...

**Comment by wiiznokes** [comment]
The build took like 3 min for the final step, whereas for other applet like my clipboard-manager, it takes like 10 secs. It finished the second i posted the issue

**Comment by wiiznokes** [comment]
And i pressed enter on the title so i didn't have the change to write a message :p

**Comment by elevenhsoft** [comment]
I know some "official" applets building also long time, I'm not sure what's the case to be honest. Never bothered ^^

**Comment by wiiznokes** [comment]
I experienced an issue like that in the past, it was because of rustc but never really understood why

**Comment by elevenhsoft** [comment]
I'm always on the latest toolchain. I don't know what's going on then. The final binary building long time but why, that's weird ^^

**Comment by wiiznokes** [comment]
It was this issue for info https://github.com/PolyMeilex/rfd/issues/126. But it's surely not related

**Comment by elevenhsoft** [comment]
Thanks, I will look into it. But now I fighting with those leaks :P
I rewritten parser for markdown and now I got rid of those Boxed string, but still it's not perfect ^^

**Comment by wiiznokes** [comment]
Might be related to https://github.com/lilyinstarlight/nixos-cosmic/issues/138. I could try to take a look if you want

**Comment by elevenhsoft** [comment]
If you want, please :)

**Comment by wiiznokes** [comment]
Oh, its definitively cause of lto=fat optimization
