### ISSUE TITLE
.desktop doesn't have the good path to icon

### ISSUE THREAD

**Issue by wiiznokes** [elevenhsoft/cosmic-ext-applet-ollama#7]
https://github.com/elevenhsoft/cosmic-ext-applet-ollama/blob/57134578c099814a4f0bef68140ab3c59fa3bb5a/data/io.github.elevenhsoft.CosmicExtAppletOllama.desktop#L8

Should be 

`Icon=io.github.elevenhsoft.CosmicExtAppletOllama-symbolic`.

Tested and it works

**Comment by elevenhsoft** [comment]
woops, it's probably result of renaming applet :P
